-- ============================================================================
-- QuimicAtomix -- Datos de ejemplo / contenido semilla (generado automaticamente)
-- Fuente: tools/generate_seed.py -- misma fuente que usa DatabaseSeeder.kt en runtime
-- ============================================================================

-- Temas
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('estados', 'Materia y Estados', 'Sólidos, líquidos y gases en acción', 'El Laboratorio necesita tu ayuda para clasificar y transformar la materia.', 'topic_estados', '#2E7DFF', 1, 1);
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('mezclas', 'Mezclas', 'Combina sustancias virtuales y descubre qué pasa', 'Quimi guarda decenas de frascos mezclados. ¡Ayúdale a identificarlos!', 'topic_mezclas', '#14C7B4', 2, 1);
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('separacion', 'Separación', 'Filtra, decanta y evapora para recuperar sustancias', 'Algunas mezclas escondidas deben separarse antes de guardarse en la estantería.', 'topic_separacion', '#7ED957', 3, 2);
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('atomos', 'Átomos', 'Los bloques diminutos que forman todo', 'Un mapa gigante de átomos apareció en la pared del laboratorio.', 'topic_atomos', '#8B5CF6', 4, 2);
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('moleculas', 'Constructor Molecular', 'Une átomos y construye moléculas reales', 'La mesa de construcción molecular de Quimi espera tus creaciones.', 'topic_moleculas', '#FF6B4A', 5, 3);
INSERT INTO chemical_topic (id, title, shortDescription, narrativeIntro, iconKey, colorHex, orderIndex, minLevelToUnlock) VALUES ('reacciones', 'Reacciones Virtuales', 'Observa cambios seguros y predice resultados', 'Algo burbujea en la cámara de reacciones. ¿Puedes predecir qué ocurrirá?', 'topic_reacciones', '#FFC145', 6, 3);

-- Sustancias virtuales
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('agua', 'estados', 'Agua', 'H2O', 'LIQUIDO', '#4FC3F7', 'Líquido transparente esencial para la vida. Cambia de estado con la temperatura.', 'sub_agua', 1, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('hielo', 'estados', 'Hielo', 'H2O (sólido)', 'SOLIDO', '#B3E5FC', 'Agua en estado sólido. Sus partículas están muy ordenadas y casi no se mueven.', 'sub_hielo', 0, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('vapor_agua', 'estados', 'Vapor de agua', 'H2O (gas)', 'GASEOSO', '#ECEFF1', 'Agua en estado gaseoso. Sus partículas se mueven libremente y ocupan más espacio.', 'sub_vapor', 0, 0, 1);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('mantequilla', 'estados', 'Mantequilla', 'Mezcla de grasas', 'SOLIDO', '#FFE082', 'Sólido blando a temperatura ambiente que se derrite fácilmente con el calor.', 'sub_mantequilla', 0, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('chocolate', 'estados', 'Chocolate', 'Mezcla de cacao', 'SOLIDO', '#8D6E63', 'Sólido que cambia a líquido al calentarse y vuelve a solidificar al enfriarse.', 'sub_chocolate', 0, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('cera_vela', 'estados', 'Cera', 'Hidrocarburos sólidos', 'SOLIDO', '#FFF9C4', 'Sólido que se ablanda y derrite con el calor; al enfriarse, vuelve a endurecerse.', 'sub_cera', 0, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('arena', 'mezclas', 'Arena', 'SiO2 (principalmente)', 'SOLIDO', '#D7B98E', 'Granos sólidos diminutos. No se disuelve en agua.', 'sub_arena', 0, 0, 3);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('aceite', 'mezclas', 'Aceite vegetal', 'Triglicéridos', 'LIQUIDO', '#FFD54F', 'Líquido que no se mezcla con el agua y flota sobre ella.', 'sub_aceite', 0, 0, 1);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('sal', 'mezclas', 'Sal de mesa', 'NaCl', 'SOLIDO', '#F5F5F5', 'Sólido cristalino que se disuelve por completo en agua.', 'sub_sal', 1, 0, 3);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('azucar', 'mezclas', 'Azúcar', 'Sacarosa', 'SOLIDO', '#FFF3E0', 'Sólido dulce que se disuelve fácilmente en agua.', 'sub_azucar', 1, 0, 3);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('limaduras_hierro', 'mezclas', 'Limaduras de hierro', 'Fe', 'SOLIDO', '#9E9E9E', 'Trocitos diminutos de hierro. No se disuelven, pero un imán los atrae.', 'sub_hierro', 0, 1, 3);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('corcho', 'mezclas', 'Corcho', 'Material vegetal', 'SOLIDO', '#D2A679', 'Sólido muy liviano que flota fácilmente en el agua.', 'sub_corcho', 0, 0, 1);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('piedritas', 'mezclas', 'Piedritas', 'Minerales variados', 'SOLIDO', '#8E8E8E', 'Sólidos duros y pesados que se hunden en el agua.', 'sub_piedritas', 0, 0, 3);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('colorante', 'mezclas', 'Colorante alimentario', 'Pigmento soluble', 'LIQUIDO', '#E91E63', 'Líquido de color intenso que se mezcla por completo con el agua.', 'sub_colorante', 1, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('harina', 'mezclas', 'Harina', 'Almidón y proteínas', 'SOLIDO', '#FFFDE7', 'Polvo fino que forma una mezcla turbia y espesa con el agua, sin disolverse del todo.', 'sub_harina', 0, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('jabon_liquido', 'mezclas', 'Jabón líquido', 'Tensioactivos', 'LIQUIDO', '#B2EBF2', 'Líquido resbaladizo que se mezcla por completo con el agua y hace espuma.', 'sub_jabon', 1, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('vinagre', 'reacciones', 'Vinagre', 'Ácido acético diluido', 'LIQUIDO', '#FFF59D', 'Líquido de olor fuerte que reacciona con el bicarbonato produciendo burbujas.', 'sub_vinagre', 1, 0, 2);
INSERT INTO virtual_substance (id, topicId, name, symbolOrFormula, state, colorHex, description, iconKey, isMiscible, isMagneticConceptual, densityTier) VALUES ('bicarbonato', 'reacciones', 'Bicarbonato de sodio', 'NaHCO3', 'SOLIDO', '#FAFAFA', 'Polvo blanco que, al mezclarse con vinagre, libera burbujas de gas de forma segura.', 'sub_bicarbonato', 1, 0, 3);

-- Atomos
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('H', 'H', 'Hidrógeno', 1, '1', 'NO_METAL', '#90CAF9', 'Es el átomo más ligero y el más abundante del universo.', 1);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('He', 'He', 'Helio', 2, '2', 'GAS_NOBLE', '#B39DDB', 'Es tan liviano que hace flotar los globos de fiesta.', 0);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('C', 'C', 'Carbono', 6, '2,4', 'NO_METAL', '#616161', 'Forma parte de todos los seres vivos, incluido tú.', 4);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('N', 'N', 'Nitrógeno', 7, '2,5', 'NO_METAL', '#64B5F6', 'Compone casi el 78% del aire que respiramos.', 3);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('O', 'O', 'Oxígeno', 8, '2,6', 'NO_METAL', '#EF5350', 'Lo necesitamos para respirar y para que el fuego arda.', 2);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('F', 'F', 'Flúor', 9, '2,7', 'HALOGENO', '#AED581', 'Ayuda a proteger los dientes en las pastas dentales.', 1);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Ne', 'Ne', 'Neón', 10, '2,8', 'GAS_NOBLE', '#F06292', 'Brilla de color naranja-rojizo en los carteles luminosos.', 0);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Na', 'Na', 'Sodio', 11, '2,8,1', 'METAL', '#FFD54F', 'Junto al cloro forma la sal de mesa que usamos al cocinar.', 1);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Mg', 'Mg', 'Magnesio', 12, '2,8,2', 'METAL', '#CE93D8', 'Le da a las plantas su color verde dentro de la clorofila.', 2);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Al', 'Al', 'Aluminio', 13, '2,8,3', 'METAL', '#B0BEC5', 'Es un metal liviano usado en latas y aviones.', 3);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Si', 'Si', 'Silicio', 14, '2,8,4', 'METALOIDE', '#A1887F', 'Es el ingrediente principal de la arena y del vidrio.', 4);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Cl', 'Cl', 'Cloro', 17, '2,8,7', 'HALOGENO', '#AED581', 'Se combina con el sodio para formar la sal común.', 1);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('K', 'K', 'Potasio', 19, '2,8,8,1', 'METAL', '#FFB74D', 'Es esencial para que tus músculos funcionen bien.', 1);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Ca', 'Ca', 'Calcio', 20, '2,8,8,2', 'METAL', '#FFF176', 'Forma parte de tus huesos y tus dientes.', 2);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Fe', 'Fe', 'Hierro', 26, '2,8,14,2', 'METAL', '#8D6E63', 'Un imán puede atraerlo; también está en tu sangre.', 2);
INSERT INTO atom (id, symbol, name, protons, electronsShellsCsv, category, colorHex, funFact, commonValence) VALUES ('Ar', 'Ar', 'Argón', 18, '2,8,8', 'GAS_NOBLE', '#4DD0E1', 'Es un gas noble que casi nunca reacciona con nada.', 0);

-- Moleculas
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_h2o', 'H2O', 'Agua', 'La molécula más importante para la vida.', 'H:2,O:1', 1, 25, 3, 'Una sola molécula de agua tiene 2 átomos de hidrógeno y 1 de oxígeno.', 'mole_h2o');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_o2', 'O2', 'Oxígeno', 'El gas que respiramos, formado por dos átomos de oxígeno unidos.', 'O:2', 1, 20, 3, 'El aire que respiras contiene oxígeno en esta forma exacta.', 'mole_o2');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_n2', 'N2', 'Nitrógeno', 'El gas más abundante del aire.', 'N:2', 1, 20, 3, 'Aunque respiramos nitrógeno todo el tiempo, nuestro cuerpo no lo usa directamente.', 'mole_n2');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_co2', 'CO2', 'Dióxido de carbono', 'El gas que exhalamos y que las plantas usan para crecer.', 'C:1,O:2', 2, 30, 4, 'Las plantas transforman el CO2 en oxígeno gracias a la luz del sol.', 'mole_co2');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_h2', 'H2', 'Hidrógeno', 'El gas más simple, formado por dos átomos de hidrógeno.', 'H:2', 1, 20, 3, 'Es el elemento más abundante de todo el universo.', 'mole_h2');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_ch4', 'CH4', 'Metano', 'Un gas formado por carbono rodeado de hidrógeno.', 'C:1,H:4', 2, 35, 4, 'Es el gas principal del biogás y del gas natural.', 'mole_ch4');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_nh3', 'NH3', 'Amoníaco', 'Una molécula con nitrógeno rodeado de hidrógeno.', 'N:1,H:3', 2, 35, 4, 'Se usa en muchos productos de limpieza del hogar.', 'mole_nh3');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_nacl', 'NaCl', 'Cloruro de sodio (sal)', 'La sal de mesa que usamos para cocinar.', 'Na:1,Cl:1', 1, 25, 3, 'Se forma con un átomo de sodio y uno de cloro perfectamente unidos.', 'mole_nacl');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_caco3', 'CaCO3', 'Carbonato de calcio', 'El compuesto principal de la tiza y las conchas marinas.', 'Ca:1,C:1,O:3', 3, 45, 5, 'Las conchas de mar y la tiza escolar están hechas principalmente de esto.', 'mole_caco3');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_sio2', 'SiO2', 'Dióxido de silicio', 'El compuesto principal de la arena y el vidrio.', 'Si:1,O:2', 3, 45, 5, 'Cuando se funde a temperaturas altísimas, se convierte en vidrio.', 'mole_sio2');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_o3', 'O3', 'Ozono', 'Una forma especial de oxígeno con tres átomos.', 'O:3', 2, 30, 4, 'En las capas altas de la atmósfera nos protege de los rayos del sol.', 'mole_o3');
INSERT INTO molecule_challenge (id, formula, commonName, description, compositionCsv, difficulty, xpReward, unlockLevel, funFact, iconKey) VALUES ('mol_c', 'C', 'Carbono puro', 'Un solo átomo de carbono, la base de la química de la vida.', 'C:1', 1, 15, 1, 'El diamante y el grafito de tu lápiz están hechos solo de carbono.', 'mole_c');

-- Experimentos (55 practicas)
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_001', 'EST-001', 'estados', 'ESTADOS', 'Sólido, líquido o gas', 'Quimi encontró tres frascos sin etiqueta: ayúdale a identificar el estado de cada uno.', 'Observa tres muestras de agua en distintos estados y clasifícalas correctamente.', 1, 'SELECCION_IMAGEN', 15, 1, 1, 'exp_clasificar_estados');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_002', 'EST-002', 'estados', 'ESTADOS', 'El viaje del hielo', 'El cubito de hielo de Quimi quiere convertirse en vapor. ¿En qué orden ocurre?', 'Ordena las etapas por las que pasa el agua al calentarse desde hielo hasta vapor.', 1, 'ORDENAR', 15, 2, 1, 'exp_viaje_hielo');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_003', 'EST-003', 'estados', 'ESTADOS', 'Mantequilla al sol', 'Quimi dejó la mantequilla fuera de la nevera. ¿Qué crees que pasará?', 'Predice qué le ocurre a la mantequilla sólida cuando aumenta la temperatura.', 1, 'PREDECIR', 15, 3, 1, 'exp_mantequilla_sol');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_004', 'EST-004', 'estados', 'ESTADOS', 'Chocolate derretido', 'Observa la animación: el chocolate sólido se calienta poco a poco en el laboratorio virtual.', 'Observa el cambio de estado del chocolate y describe lo que ves.', 1, 'OBSERVAR', 15, 4, 1, 'exp_chocolate_derretido');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_005', 'EST-005', 'estados', 'ESTADOS', 'El armario de los estados', 'Quimi necesita ordenar su armario de sustancias según su estado de la materia.', 'Clasifica seis sustancias cotidianas en sólido, líquido o gaseoso.', 2, 'CLASIFICAR', 20, 5, 1, 'exp_armario_estados');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_006', 'EST-006', 'estados', 'ESTADOS', 'La vela se enfría', 'La cera líquida de una vela virtual empieza a enfriarse. ¿Qué pasos sigue hasta endurecerse?', 'Ordena el proceso de solidificación de la cera al enfriarse.', 2, 'ORDENAR', 20, 6, 1, 'exp_vela_enfria');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_007', 'EST-007', 'estados', 'ESTADOS', 'El termómetro del laboratorio', 'Mueve el control de temperatura y observa cuándo el agua se congela.', 'Configura la temperatura conceptual hasta encontrar el punto de congelación del agua.', 2, 'CONFIGURAR', 20, 7, 2, 'exp_termometro');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_008', 'EST-008', 'estados', 'ESTADOS', 'El vapor que vuelve', 'El vapor de la olla virtual choca con una tapa fría. ¿Qué crees que pasará?', 'Predice qué sucede cuando el vapor de agua se enfría de repente.', 2, 'PREDECIR', 20, 8, 2, 'exp_vapor_vuelve');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_009', 'EST-009', 'estados', 'ESTADOS', 'Propiedades conectadas', 'Cada estado de la materia tiene una propiedad especial. ¿Puedes unirlas?', 'Conecta cada estado de la materia con la propiedad que lo describe mejor.', 2, 'CONECTAR', 20, 9, 2, 'exp_propiedades_conectadas');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_est_010', 'EST-010', 'estados', 'ESTADOS', 'Repaso: el gran clasificador', 'Última prueba de la Academia de Estados: clasifica todo lo que has aprendido.', 'Repasa clasificando seis sustancias nuevas según su estado de la materia.', 2, 'CLASIFICAR', 25, 10, 2, 'exp_repaso_estados');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_001', 'MEZ-001', 'mezclas', 'MEZCLA', 'Arena en el vaso', 'Quimi vertió arena en agua. ¿Se mezclará de verdad?', 'Combina agua y arena para descubrir si forman una mezcla homogénea o heterogénea.', 1, 'ARRASTRAR_SOLTAR', 20, 1, 1, 'exp_mezcla_agua_arena');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_002', 'MEZ-002', 'mezclas', 'MEZCLA', 'Piedritas al fondo', 'Unas piedritas cayeron en el vaso de agua de Quimi.', 'Combina agua y piedritas para descubrir si forman una mezcla homogénea o heterogénea.', 1, 'ARRASTRAR_SOLTAR', 20, 2, 1, 'exp_mezcla_agua_piedritas');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_003', 'MEZ-003', 'mezclas', 'MEZCLA', 'Agua y aceite', 'El aceite parece flotar sobre el agua. ¿Por qué pasará eso?', 'Combina agua y aceite para descubrir si forman una mezcla homogénea o heterogénea.', 1, 'ARRASTRAR_SOLTAR', 20, 3, 1, 'exp_mezcla_agua_aceite');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_004', 'MEZ-004', 'mezclas', 'MEZCLA', 'El corcho flotante', 'Un trocito de corcho cayó al vaso de agua.', 'Combina agua y corcho para descubrir si forman una mezcla homogénea o heterogénea.', 1, 'ARRASTRAR_SOLTAR', 20, 4, 1, 'exp_mezcla_agua_corcho');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_005', 'MEZ-005', 'mezclas', 'MEZCLA', 'Nube de harina', 'La harina forma una nube blanca dentro del agua.', 'Combina agua y harina para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 5, 1, 'exp_mezcla_agua_harina');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_006', 'MEZ-006', 'mezclas', 'MEZCLA', 'La sal desaparece', 'Quimi disolvió sal en agua y ya no puede verla.', 'Combina agua y sal para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 6, 1, 'exp_mezcla_agua_sal');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_007', 'MEZ-007', 'mezclas', 'MEZCLA', 'Agua dulce', 'El azúcar se disolvió por completo en el vaso de Quimi.', 'Combina agua y azucar para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 7, 1, 'exp_mezcla_agua_azucar');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_008', 'MEZ-008', 'mezclas', 'MEZCLA', 'Agua de colores', 'Una gota de colorante se esparce en el agua.', 'Combina agua y colorante para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 8, 1, 'exp_mezcla_agua_colorante');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_009', 'MEZ-009', 'mezclas', 'MEZCLA', 'Burbujas de jabón', 'El jabón líquido se mezcló con agua y generó espuma.', 'Combina agua y jabon liquido para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 9, 1, 'exp_mezcla_agua_jabon_liquido');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mez_010', 'MEZ-010', 'mezclas', 'MEZCLA', 'Arena en el aceite', 'Esta vez la arena cae dentro de un vaso de aceite.', 'Combina aceite y arena para descubrir si forman una mezcla homogénea o heterogénea.', 2, 'ARRASTRAR_SOLTAR', 25, 10, 1, 'exp_mezcla_aceite_arena');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_001', 'SEP-001', 'separacion', 'SEPARACION', 'Rescata el agua limpia', 'Esta mezcla de agua y arena debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar agua y arena: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 1, 2, 'exp_separar_agua_arena');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_002', 'SEP-002', 'separacion', 'SEPARACION', 'Cuela las piedritas', 'Esta mezcla de agua y piedritas debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar agua y piedritas: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 2, 2, 'exp_separar_agua_piedritas');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_003', 'SEP-003', 'separacion', 'SEPARACION', 'Separa las capas', 'Esta mezcla de agua y aceite debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar agua y aceite: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 3, 2, 'exp_separar_agua_aceite');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_004', 'SEP-004', 'separacion', 'SEPARACION', 'Recoge el corcho', 'Esta mezcla de agua y corcho debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar agua y corcho: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 4, 2, 'exp_separar_agua_corcho');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_005', 'SEP-005', 'separacion', 'SEPARACION', 'Filtra la nube blanca', 'Esta mezcla de agua y harina debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar agua y harina: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 5, 2, 'exp_separar_agua_harina');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_006', 'SEP-006', 'separacion', 'SEPARACION', 'Limpia el aceite', 'Esta mezcla de aceite y arena debe separarse antes de guardarse en la estantería.', 'Elige la técnica correcta para separar aceite y arena: filtración, decantación o evaporación.', 2, 'SELECCION_IMAGEN', 25, 6, 2, 'exp_separar_aceite_arena');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_007', 'SEP-007', 'separacion', 'SEPARACION', 'Pasos de la evaporación', 'Quimi quiere recuperar la sal disuelta en agua. ¿En qué orden se hace?', 'Ordena correctamente los pasos del proceso de evaporación conceptual.', 2, 'ORDENAR', 25, 7, 2, 'exp_pasos_evaporacion');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_sep_008', 'SEP-008', 'separacion', 'SEPARACION', 'Pasos de la filtración', 'Una mezcla turbia espera en la mesa de Quimi. ¿Cómo se filtra correctamente?', 'Ordena correctamente los pasos del proceso de filtración conceptual.', 1, 'ORDENAR', 20, 8, 2, 'exp_pasos_filtracion');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_001', 'ATO-001', 'atomos', 'ATOMO', 'El mapa de los átomos', 'Un mapa gigante de átomos apareció en la pared del laboratorio de Quimi.', 'Clasifica seis átomos según su categoría: metal, no metal o gas noble.', 1, 'CLASIFICAR', 20, 1, 2, 'exp_mapa_atomos');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_002', 'ATO-002', 'atomos', 'ATOMO', 'Símbolo y nombre', 'Cada átomo tiene un símbolo especial. ¿Puedes emparejarlos con su nombre?', 'Conecta el símbolo químico de cada átomo con su nombre correcto.', 1, 'CONECTAR', 20, 2, 2, 'exp_simbolo_nombre');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_003', 'ATO-003', 'atomos', 'ATOMO', 'Orden de protones', 'Quimi mezcló las tarjetas de átomos. ¿Puedes ordenarlas por número de protones?', 'Ordena cuatro átomos de menor a mayor número de protones.', 2, 'ORDENAR', 25, 3, 2, 'exp_orden_protones');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_004', 'ATO-004', 'atomos', 'ATOMO', 'Capas de electrones', 'Observa cómo los electrones del sodio se acomodan en capas alrededor del núcleo.', 'Observa la animación de capas electrónicas y responde cuántas capas tiene el átomo.', 2, 'OBSERVAR', 25, 4, 2, 'exp_capas_electrones');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_005', 'ATO-005', 'atomos', 'ATOMO', 'Encuentra el átomo', 'Quimi describe un átomo con pistas. ¿Puedes encontrarlo en la mesa periódica virtual?', 'Selecciona el átomo correcto a partir de una pista visual sobre sus propiedades.', 2, 'SELECCION_IMAGEN', 25, 5, 2, 'exp_encuentra_atomo');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_006', 'ATO-006', 'atomos', 'ATOMO', 'La última capa', 'Quimi quiere saber cuántos electrones tiene la capa más externa de un átomo.', 'Predice cuántos electrones hay en la última capa del átomo de oxígeno.', 3, 'PREDECIR', 30, 6, 3, 'exp_ultima_capa');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_007', 'ATO-007', 'atomos', 'ATOMO', 'Metal o no metal', 'Quimi separa sus tarjetas de átomos en dos grupos: metales y no metales.', 'Clasifica cuatro átomos comparando sus propiedades como metal o no metal.', 2, 'CLASIFICAR', 25, 7, 2, 'exp_metal_no_metal');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_ato_008', 'ATO-008', 'atomos', 'ATOMO', 'Repaso: gran examen atómico', 'Última prueba de la Academia de Átomos antes de pasar al constructor molecular.', 'Responde preguntas de repaso sobre los átomos aprendidos.', 2, 'OPCION_MULTIPLE', 25, 8, 3, 'exp_repaso_atomos');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_001', 'MOL-001', 'moleculas', 'MOLECULA', 'Fórmula y nombre', 'Antes de construir, Quimi quiere que reconozcas las fórmulas más comunes.', 'Conecta la fórmula química de cada molécula con su nombre común.', 1, 'CONECTAR', 20, 1, 3, 'exp_formula_nombre');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_002', 'MOL-002', 'moleculas', 'MOLECULA', 'Cuenta los átomos', 'Quimi te muestra una fórmula. ¿Cuántos átomos totales tiene?', 'Predice cuántos átomos en total forman la molécula de metano (CH4).', 2, 'PREDECIR', 25, 2, 3, 'exp_cuenta_atomos');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_003', 'MOL-003', 'moleculas', 'MOLECULA', '¿Tiene carbono?', 'Quimi separa las moléculas orgánicas de las que no lo son.', 'Clasifica moléculas según si contienen o no átomos de carbono.', 2, 'CLASIFICAR', 25, 3, 3, 'exp_tiene_carbono');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_004', 'MOL-004', 'moleculas', 'MOLECULA', 'De menor a mayor', 'Quimi mezcló tarjetas de moléculas. ¿Puedes ordenarlas por cantidad de átomos?', 'Ordena tres moléculas de menor a mayor cantidad total de átomos.', 2, 'ORDENAR', 25, 4, 3, 'exp_menor_mayor');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_005', 'MOL-005', 'moleculas', 'MOLECULA', 'Encuentra la molécula', 'Quimi describe una molécula con una pista visual. ¿Puedes reconocerla?', 'Selecciona la molécula correcta a partir de una pista sobre su función.', 1, 'SELECCION_IMAGEN', 20, 5, 3, 'exp_encuentra_molecula');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_006', 'MOL-006', 'moleculas', 'MOLECULA', 'Observa la estructura', 'Observa cómo se representan los átomos unidos dentro de una molécula de agua.', 'Observa la animación de la estructura del agua y responde una pregunta.', 1, 'OBSERVAR', 20, 6, 3, 'exp_observa_estructura');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_007', 'MOL-007', 'moleculas', 'MOLECULA', 'Piezas necesarias', 'Antes de construir en la mesa grande, arma mentalmente la lista de piezas.', 'Identifica qué átomos necesitarás para construir una molécula de amoníaco (NH3).', 2, 'CONSTRUIR', 30, 7, 3, 'exp_piezas_necesarias');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_mol_008', 'MOL-008', 'moleculas', 'MOLECULA', 'Repaso molecular', 'Última prueba antes de pasar a la mesa de construcción molecular completa.', 'Responde una pregunta de repaso general sobre moléculas.', 2, 'OPCION_MULTIPLE', 25, 8, 3, 'exp_repaso_moleculas');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_001', 'REA-001', 'reacciones', 'REACCION', 'Vinagre y bicarbonato', 'Quimi va a combinar vinagre y bicarbonato en la cámara de reacciones. ¿Qué pasará?', 'Predice qué ocurre al combinar vinagre y bicarbonato de forma segura y virtual.', 1, 'PREDECIR', 20, 1, 3, 'exp_vinagre_bicarbonato');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_002', 'REA-002', 'reacciones', 'REACCION', 'Observa la efervescencia', 'Observa con atención la animación de la reacción entre vinagre y bicarbonato.', 'Observa la efervescencia y responde qué señal indica que ocurrió una reacción.', 1, 'OBSERVAR', 20, 2, 3, 'exp_observa_efervescencia');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_003', 'REA-003', 'reacciones', 'REACCION', 'Más o menos bicarbonato', 'Mueve el control de cantidad de bicarbonato y observa cómo cambia la reacción.', 'Configura la cantidad de bicarbonato y observa el efecto sobre la efervescencia.', 2, 'CONFIGURAR', 25, 3, 3, 'exp_cantidad_bicarbonato');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_004', 'REA-004', 'reacciones', 'REACCION', 'El hierro se oxida', 'Con el paso del tiempo, un clavo de hierro virtual cambia lentamente de color.', 'Ordena las etapas de la oxidación lenta del hierro al estar en contacto con el aire.', 2, 'ORDENAR', 25, 4, 3, 'exp_hierro_oxida');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_005', 'REA-005', 'reacciones', 'REACCION', 'Lo que necesita una planta', 'Quimi riega una planta virtual y quiere saber qué necesita para producir su alimento.', 'Predice qué elementos necesita una planta para realizar la fotosíntesis.', 2, 'PREDECIR', 25, 5, 3, 'exp_planta_fotosintesis');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_006', 'REA-006', 'reacciones', 'REACCION', 'Rápida o lenta', 'Algunas reacciones ocurren en segundos, otras tardan años. Clasifícalas.', 'Clasifica reacciones cotidianas según sean rápidas o lentas.', 2, 'CLASIFICAR', 25, 6, 3, 'exp_rapida_lenta');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_007', 'REA-007', 'reacciones', 'REACCION', 'Reactivos y productos', 'Toda reacción tiene ingredientes iniciales y resultados finales. Conéctalos.', 'Conecta cada combinación de reactivos con el producto que genera.', 2, 'CONECTAR', 25, 7, 3, 'exp_reactivos_productos');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_008', 'REA-008', 'reacciones', 'REACCION', 'El repollo mágico', 'El jugo de repollo morado cambia de color según lo que le agregues: es un indicador natural.', 'Observa cómo el jugo de repollo morado cambia de color al mezclarse con vinagre.', 2, 'OBSERVAR', 25, 8, 4, 'exp_repollo_magico');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_009', 'REA-009', 'reacciones', 'REACCION', 'Combinar dos gases', 'Quimi combina conceptualmente hidrógeno y oxígeno en la cámara segura. ¿Qué se forma?', 'Predice qué molécula se puede formar al combinar hidrógeno y oxígeno.', 3, 'PREDECIR', 30, 9, 4, 'exp_combinar_gases');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_010', 'REA-010', 'reacciones', 'REACCION', 'Señales de reacción', 'Quimi te muestra distintas imágenes. ¿Cuál demuestra que ocurrió una reacción química?', 'Selecciona la imagen que mejor representa una señal de reacción química.', 2, 'SELECCION_IMAGEN', 25, 10, 4, 'exp_senales_reaccion');
INSERT INTO experiment (id, code, topicId, type, title, narrativeHook, description, difficulty, primaryInteraction, xpReward, orderIndex, requiredLevel, iconKey) VALUES ('exp_rea_011', 'REA-011', 'reacciones', 'REACCION', 'Repaso: gran examen de reacciones', 'Última prueba de la cámara de reacciones antes de graduarte del laboratorio.', 'Responde una pregunta de repaso general sobre reacciones virtuales.', 2, 'OPCION_MULTIPLE', 25, 11, 4, 'exp_repaso_reacciones');

-- Pasos de experimento
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_001', 1, 'Arrastra cada imagen al estado que le corresponde: hielo, agua líquida y vapor.', 'SELECCION_IMAGEN', 'hielo,agua_liquida,vapor', 'solido,liquido,gaseoso', '¡Exacto! El hielo es sólido, el agua líquida fluye y el vapor es un gas.', 'Repasa: el hielo mantiene su forma, el agua líquida se adapta al recipiente y el vapor se expande.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_002', 1, 'Ordena las etapas de calentamiento del agua.', 'ORDENAR', 'vapor,agua_liquida,hielo', 'hielo,agua_liquida,vapor', '¡Correcto! El hielo se derrite (fusión) y luego se evapora (evaporación).', 'El orden correcto es: primero sólido, luego líquido y finalmente gas.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_003', 1, '¿Qué le pasará a la mantequilla si sube la temperatura?', 'PREDECIR', 'se_derrite,se_endurece,desaparece', 'se_derrite', '¡Bien predicho! El calor hace que la mantequilla pase de sólido a líquido.', 'El calor no hace desaparecer la materia: la mantequilla se derrite, no se esfuma.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_004', 1, 'Después de observar, indica qué cambio de estado ocurrió.', 'OBSERVAR', 'fusion,evaporacion,condensacion', 'fusion', '¡Correcto! El chocolate pasó de sólido a líquido: eso es fusión.', 'El chocolate se derritió: ese cambio de sólido a líquido se llama fusión.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_005', 1, 'Arrastra cada sustancia a la caja de su estado correcto: hielo, agua, vapor, mantequilla, chocolate, cera.', 'CLASIFICAR', 'hielo,agua,vapor_agua,mantequilla,chocolate,cera_vela', 'hielo,mantequilla,chocolate,cera_vela|agua|vapor_agua', '¡Gran trabajo clasificando! La mayoría eran sólidos, uno líquido y uno gaseoso.', 'Recuerda: a temperatura ambiente el hielo, la mantequilla, el chocolate y la cera son sólidos.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_006', 1, 'Ordena las etapas de la cera al enfriarse.', 'ORDENAR', 'cera_solida,cera_tibia,cera_liquida', 'cera_liquida,cera_tibia,cera_solida', '¡Perfecto! La cera pasa de líquida a tibia y finalmente se solidifica del todo.', 'El orden correcto es: líquida primero, después tibia, y sólida al final.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_007', 1, 'Mueve el control hasta la zona donde el agua se congela.', 'CONFIGURAR', 'caliente,templado,frio_congelante', 'frio_congelante', '¡Así es! A temperaturas muy bajas, el agua líquida se convierte en hielo.', 'Debes bajar mucho la temperatura: el agua se congela en la zona más fría.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_008', 1, '¿Qué pasa cuando el vapor toca una superficie fría?', 'PREDECIR', 'se_condensa,se_congela,desaparece', 'se_condensa', '¡Correcto! El vapor se enfría y vuelve a ser gotitas de agua líquida: condensación.', 'El vapor no desaparece: al enfriarse forma gotitas de agua líquida, eso es condensación.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_009', 1, 'Conecta: sólido, líquido y gaseoso con su propiedad correspondiente.', 'CONECTAR', 'solido-forma_fija,liquido-toma_forma_recipiente,gaseoso-se_expande_todo', 'solido-forma_fija,liquido-toma_forma_recipiente,gaseoso-se_expande_todo', '¡Excelente conexión! Cada estado se comporta de forma distinta según sus partículas.', 'Piensa cómo se comportan las partículas: muy juntas y ordenadas, algo libres, o muy separadas.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_est_010', 1, 'Clasifica: jugo helado, aire, roca, aceite, nube de vapor y una moneda.', 'CLASIFICAR', 'jugo_helado,aire,roca,aceite,nube_vapor,moneda', 'jugo_helado,roca,moneda|aceite|aire,nube_vapor', '¡Repaso superado! Distinguiste correctamente sólidos, líquidos y gases variados.', 'Recuerda: los sólidos mantienen forma propia, los líquidos fluyen y los gases se expanden.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_001', 1, 'Arrastra agua y arena al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,arena', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_002', 1, 'Arrastra agua y piedritas al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,piedritas', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_003', 1, 'Arrastra agua y aceite al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,aceite', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_004', 1, 'Arrastra agua y corcho al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,corcho', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_005', 1, 'Arrastra agua y harina al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,harina', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_006', 1, 'Arrastra agua y sal al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,sal', 'homogenea', '¡Correcto! Es una mezcla homogénea: no se distinguen las partes por separado.', 'Fíjate bien: si no puedes distinguir las partes, la mezcla es homogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_007', 1, 'Arrastra agua y azucar al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,azucar', 'homogenea', '¡Correcto! Es una mezcla homogénea: no se distinguen las partes por separado.', 'Fíjate bien: si no puedes distinguir las partes, la mezcla es homogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_008', 1, 'Arrastra agua y colorante al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,colorante', 'homogenea', '¡Correcto! Es una mezcla homogénea: no se distinguen las partes por separado.', 'Fíjate bien: si no puedes distinguir las partes, la mezcla es homogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_009', 1, 'Arrastra agua y jabon_liquido al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'agua,jabon_liquido', 'homogenea', '¡Correcto! Es una mezcla homogénea: no se distinguen las partes por separado.', 'Fíjate bien: si no puedes distinguir las partes, la mezcla es homogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mez_010', 1, 'Arrastra aceite y arena al vaso de mezcla y observa el resultado.', 'ARRASTRAR_SOLTAR', 'aceite,arena', 'heterogenea', '¡Correcto! Es una mezcla heterogénea: se pueden distinguir sus partes a simple vista.', 'Fíjate bien: si puedes distinguir las partes por separado, la mezcla es heterogénea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_001', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'filtracion', '¡Correcto! La filtración es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la filtración.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_002', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'filtracion', '¡Correcto! La filtración es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la filtración.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_003', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'decantacion', '¡Correcto! La decantación es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la decantación.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_004', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'decantacion', '¡Correcto! La decantación es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la decantación.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_005', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'filtracion', '¡Correcto! La filtración es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la filtración.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_006', 1, 'Selecciona la técnica correcta de separación para esta mezcla.', 'SELECCION_IMAGEN', 'filtracion,decantacion,evaporacion', 'filtracion', '¡Correcto! La filtración es la técnica ideal para este caso.', 'Piensa en las propiedades de la mezcla: aquí la técnica correcta era la filtración.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_007', 1, 'Ordena los pasos: calentar suavemente, esperar a que el agua se evapore, recoger el sólido restante.', 'ORDENAR', 'recoger_solido,calentar_suavemente,esperar_evaporacion', 'calentar_suavemente,esperar_evaporacion,recoger_solido', '¡Excelente secuencia! Así se recupera el sólido disuelto en una mezcla homogénea.', 'El orden correcto es: calentar, esperar a que el agua se vaya, y recoger lo que queda.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_sep_008', 1, 'Ordena los pasos: verter la mezcla sobre el filtro, colocar el filtro en el embudo, recoger el líquido limpio.', 'ORDENAR', 'recoger_liquido,colocar_filtro,verter_mezcla', 'colocar_filtro,verter_mezcla,recoger_liquido', '¡Muy bien! Primero se prepara el filtro, luego se vierte, y al final se recoge el resultado.', 'El orden correcto es: colocar el filtro, verter la mezcla, y recoger el líquido limpio.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_001', 1, 'Clasifica: H, O, Na, He, Fe, Ne según su categoría.', 'CLASIFICAR', 'H,O,Na,He,Fe,Ne', 'H,O|Na,Fe|He,Ne', '¡Bien hecho! Distinguiste no metales, metales y gases nobles correctamente.', 'Recuerda: H y O son no metales, Na y Fe son metales, He y Ne son gases nobles.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_002', 1, 'Conecta: H-Hidrógeno, O-Oxígeno, C-Carbono, N-Nitrógeno.', 'CONECTAR', 'H-Hidrogeno,O-Oxigeno,C-Carbono,N-Nitrogeno', 'H-Hidrogeno,O-Oxigeno,C-Carbono,N-Nitrogeno', '¡Perfecto emparejamiento! Ya reconoces los símbolos más comunes.', 'Revisa con calma: cada símbolo químico corresponde a un único nombre.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_003', 1, 'Ordena de menor a mayor número de protones: O, H, C, N.', 'ORDENAR', 'O,C,N,H', 'H,C,N,O', '¡Correcto! H tiene 1 protón, C tiene 6, N tiene 7 y O tiene 8.', 'Recuerda el número de protones: H=1, C=6, N=7, O=8.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_004', 1, '¿Cuántas capas de electrones observaste en el átomo de sodio (Na)?', 'OBSERVAR', '1,2,3', '3', '¡Correcto! El sodio tiene tres capas: 2, 8 y 1 electrón respectivamente.', 'Cuenta de nuevo: el sodio distribuye sus electrones en tres capas.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_005', 1, 'Pista: soy un gas noble que brilla de color naranja en los carteles luminosos. ¿Quién soy?', 'SELECCION_IMAGEN', 'He,Ne,Ar', 'Ne', '¡Correcto! El neón es famoso por su brillo naranja-rojizo en los letreros.', 'Piensa en los carteles luminosos de neón: ese gas noble es el que buscas.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_006', 1, 'El oxígeno tiene capas 2,6. ¿Cuántos electrones hay en su última capa?', 'PREDECIR', '2,6,8', '6', '¡Exacto! La última capa del oxígeno tiene 6 electrones.', 'Observa la secuencia 2,6: el último número es el de la capa más externa.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_007', 1, 'Clasifica: Fe, Ca, O, N en metales o no metales.', 'CLASIFICAR', 'Fe,Ca,O,N', 'Fe,Ca|O,N', '¡Bien clasificado! Fe y Ca son metales; O y N son no metales.', 'Recuerda: los metales suelen ser brillantes y conducir electricidad; O y N no lo son.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_ato_008', 1, '¿Cuál de estos NO es un gas noble?', 'OPCION_MULTIPLE', 'He,Ne,Na', 'Na', '¡Correcto! El sodio (Na) es un metal, no un gas noble.', 'Repasa: He y Ne son gases nobles; Na es un metal.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_001', 1, 'Conecta: H2O-Agua, CO2-Dióxido de carbono, O2-Oxígeno, NaCl-Sal.', 'CONECTAR', 'H2O-Agua,CO2-Dioxido_de_carbono,O2-Oxigeno,NaCl-Sal', 'H2O-Agua,CO2-Dioxido_de_carbono,O2-Oxigeno,NaCl-Sal', '¡Excelente! Ya reconoces las fórmulas de moléculas muy comunes.', 'Piensa en su uso diario: una es para respirar, otra para cocinar, otra es agua.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_002', 1, 'La fórmula CH4 tiene 1 átomo de carbono y 4 de hidrógeno. ¿Cuántos átomos en total?', 'PREDECIR', '4,5,6', '5', '¡Correcto! 1 carbono + 4 hidrógenos = 5 átomos en total.', 'Suma con cuidado: 1 átomo de carbono más 4 de hidrógeno.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_003', 1, 'Clasifica: CO2, H2O, CH4, O2 según si contienen carbono.', 'CLASIFICAR', 'CO2,H2O,CH4,O2', 'CO2,CH4|H2O,O2', '¡Correcto! CO2 y CH4 tienen carbono; H2O y O2 no lo tienen.', 'Fíjate en la letra C dentro de la fórmula: indica presencia de carbono.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_004', 1, 'Ordena de menor a mayor cantidad de átomos: H2O (3), O2 (2), CH4 (5).', 'ORDENAR', 'H2O,CH4,O2', 'O2,H2O,CH4', '¡Correcto! O2 tiene 2 átomos, H2O tiene 3 y CH4 tiene 5.', 'Cuenta átomo por átomo en cada fórmula antes de ordenar.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_005', 1, 'Pista: las plantas la transforman en oxígeno gracias a la luz del sol. ¿Cuál es?', 'SELECCION_IMAGEN', 'O2,CO2,N2', 'CO2', '¡Correcto! El dióxido de carbono es transformado en oxígeno por las plantas.', 'Piensa en la fotosíntesis: las plantas absorben este gas para producir oxígeno.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_006', 1, '¿Cuántos átomos de hidrógeno viste unidos al oxígeno?', 'OBSERVAR', '1,2,3', '2', '¡Correcto! El agua tiene 2 átomos de hidrógeno unidos a 1 de oxígeno.', 'Vuelve a observar: cuenta los átomos pequeños unidos al átomo central.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_007', 1, 'Selecciona los TIPOS de átomos necesarios para construir NH3 (nitrógeno e hidrógeno).', 'CONSTRUIR', 'N,H,O,C', 'N,H', '¡Perfecto! NH3 se construye combinando átomos de nitrógeno e hidrógeno.', 'Revisa la fórmula NH3: la N indica nitrógeno y la H indica hidrógeno.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_mol_008', 1, '¿Cuál de estas fórmulas corresponde al agua?', 'OPCION_MULTIPLE', 'CO2,H2O,O2', 'H2O', '¡Correcto! H2O es la fórmula del agua.', 'Repasa: la fórmula del agua combina hidrógeno y oxígeno como H2O.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_001', 1, '¿Qué crees que pasará al combinar vinagre y bicarbonato?', 'PREDECIR', 'burbujas,nada,se_congela', 'burbujas', '¡Correcto! Se forman burbujas: es una reacción que libera gas de forma segura.', 'Piensa en experimentos caseros clásicos: esta combinación siempre burbujea.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_002', 1, '¿Qué señal viste que indica que ocurrió una reacción química?', 'OBSERVAR', 'burbujas,cambio_color,ningun_cambio', 'burbujas', '¡Correcto! Las burbujas son una señal clásica de reacción química.', 'Vuelve a observar con calma: algo se liberó en forma de pequeñas burbujas.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_003', 1, 'Mueve el control hasta encontrar la cantidad que produce más burbujas.', 'CONFIGURAR', 'poca,media,mucha', 'mucha', '¡Correcto! A mayor cantidad de bicarbonato, más burbujas se producen.', 'Prueba con más cantidad: la reacción es más intensa cuando hay más bicarbonato.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_004', 1, 'Ordena las etapas: hierro cubierto de óxido, hierro brillante, hierro con manchas rojizas.', 'ORDENAR', 'hierro_con_manchas,hierro_cubierto_oxido,hierro_brillante', 'hierro_brillante,hierro_con_manchas,hierro_cubierto_oxido', '¡Correcto! Con el tiempo el hierro brillante desarrolla manchas y luego se oxida por completo.', 'El orden correcto va del hierro brillante y nuevo hasta quedar completamente oxidado.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_005', 1, '¿Qué necesita la planta, además de agua, para hacer fotosíntesis?', 'PREDECIR', 'luz_solar,oscuridad,frio_extremo', 'luz_solar', '¡Correcto! La luz solar es esencial para que la planta produzca su alimento.', 'Piensa en dónde crecen mejor las plantas: necesitan luz solar para fotosintetizar.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_006', 1, 'Clasifica: vinagre+bicarbonato, oxidación del hierro, quema de un fósforo, maduración de una fruta.', 'CLASIFICAR', 'vinagre_bicarbonato,oxidacion_hierro,quema_fosforo,maduracion_fruta', 'vinagre_bicarbonato,quema_fosforo|oxidacion_hierro,maduracion_fruta', '¡Correcto! Unas reacciones son casi inmediatas y otras tardan días o años.', 'Piensa en el tiempo que tardan: algunas son instantáneas, otras muy graduales.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_007', 1, 'Conecta: vinagre+bicarbonato-burbujas_de_gas, hierro+aire_humedo-oxido.', 'CONECTAR', 'vinagre_bicarbonato-burbujas_de_gas,hierro_aire_humedo-oxido', 'vinagre_bicarbonato-burbujas_de_gas,hierro_aire_humedo-oxido', '¡Correcto! Cada combinación de reactivos produce un resultado característico.', 'Piensa en lo que observaste en experimentos anteriores sobre estas combinaciones.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_008', 1, '¿A qué color cambió el jugo de repollo morado al mezclarlo con vinagre?', 'OBSERVAR', 'rosado,verde,igual', 'rosado', '¡Correcto! El jugo de repollo morado se vuelve rosado en contacto con sustancias ácidas.', 'Vuelve a observar la animación: el color cambia hacia tonos rosados o rojizos.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_009', 1, 'Al combinar hidrógeno y oxígeno de forma equilibrada, ¿qué molécula se forma?', 'PREDECIR', 'agua,sal,azucar', 'agua', '¡Correcto! Hidrógeno y oxígeno combinados forman agua (H2O).', 'Recuerda la fórmula del agua: está hecha justamente de estos dos elementos.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_010', 1, 'Selecciona la señal que indica que ocurrió una reacción química.', 'SELECCION_IMAGEN', 'burbujeo,agua_quieta,piedra_inmovil', 'burbujeo', '¡Correcto! El burbujeo es una señal clara de que se liberó un gas por reacción.', 'Busca cambios visibles: burbujas, cambio de color o de temperatura indican reacción.');
INSERT INTO experiment_step (experimentId, stepIndex, instruction, interactionType, optionsCsv, correctAnswerCsv, explanationCorrect, explanationIncorrect) VALUES ('exp_rea_011', 1, '¿Cuál de estas NO es una señal típica de reacción química?', 'OPCION_MULTIPLE', 'burbujas,cambio_color,silencio_total', 'silencio_total', '¡Correcto! El silencio total no indica ningún cambio químico observable.', 'Repasa: burbujas y cambios de color sí son señales de reacción; la ausencia de cambio no lo es.');

-- Combinaciones de mezclas
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_001', 'agua', 'arena', 0, 'filtracion', 'La arena no se disuelve: queda suspendida y se puede filtrar.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_002', 'agua', 'piedritas', 0, 'filtracion', 'Las piedritas se hunden enteras; un colador las separa fácilmente.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_003', 'agua', 'aceite', 0, 'decantacion', 'El aceite flota formando una capa separada sobre el agua.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_004', 'agua', 'corcho', 0, 'decantacion', 'El corcho flota; se puede retirar con cuidado desde arriba.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_005', 'agua', 'harina', 0, 'filtracion', 'La harina forma una mezcla turbia que un filtro fino puede retener.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_006', 'agua', 'sal', 1, 'evaporacion', 'La sal se disuelve por completo; al evaporar el agua, la sal reaparece.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_007', 'agua', 'azucar', 1, 'evaporacion', 'El azúcar se disuelve por completo, formando una mezcla homogénea.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_008', 'agua', 'colorante', 1, 'evaporacion', 'El colorante se reparte de manera uniforme en toda el agua.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_009', 'agua', 'jabon_liquido', 1, 'evaporacion', 'El jabón se integra por completo formando una mezcla homogénea con espuma.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_mez_010', 'aceite', 'arena', 0, 'filtracion', 'La arena se hunde en el aceite y puede retenerse con un filtro.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_001', 'agua', 'arena', 0, 'filtracion', 'Mezcla heterogenea que debe separarse con filtracion.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_002', 'agua', 'piedritas', 0, 'filtracion', 'Mezcla heterogenea que debe separarse con filtracion.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_003', 'agua', 'aceite', 0, 'decantacion', 'Mezcla heterogenea que debe separarse con decantacion.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_004', 'agua', 'corcho', 0, 'decantacion', 'Mezcla heterogenea que debe separarse con decantacion.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_005', 'agua', 'harina', 0, 'filtracion', 'Mezcla heterogenea que debe separarse con filtracion.');
INSERT INTO experiment_combination (experimentId, substanceAId, substanceBId, isHomogeneous, recommendedSeparationTechnique, resultDescription) VALUES ('exp_sep_006', 'aceite', 'arena', 0, 'filtracion', 'Mezcla heterogenea que debe separarse con filtracion.');

-- Escenarios de seguridad (35)
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_01', 'EN_CASA', 'Frasco sin etiqueta', 'Encuentras un frasco de limpieza sin etiqueta bajo el fregadero.', 'No tocarlo y avisar a un adulto', 'Olerlo para adivinar qué es|Probar un poco con el dedo', 'Nunca debes tocar ni probar sustancias desconocidas: un adulto sabe identificarlas de forma segura.', 'saf_casa_01', 1);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_02', 'EN_CASA', 'Hermanito curioso', 'Ves a tu hermanito pequeño jugando cerca de productos de limpieza.', 'Alejarlo y avisar a un adulto', 'Dejarlo seguir jugando|Quitarle el envase y guardarlo tú mismo', 'Los productos de limpieza deben estar fuera del alcance de los más pequeños; un adulto debe encargarse.', 'saf_casa_02', 2);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_03', 'EN_CASA', 'Tapa mal cerrada', 'Un envase de detergente tiene la tapa mal cerrada y podría derramarse.', 'Avisar a un adulto para que lo cierre bien', 'Cerrarlo tú mismo apretando fuerte|Ignorarlo, no es importante', 'Aunque parezca sencillo, es mejor que un adulto manipule envases de productos químicos del hogar.', 'saf_casa_03', 3);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_04', 'EN_CASA', 'Humo en el enchufe', 'Ves humo saliendo de un enchufe de la pared.', 'Alejarte y avisar a un adulto de inmediato', 'Tocar el enchufe para ver qué pasa|Echarle agua', 'El humo eléctrico es peligroso: aléjate y pide ayuda a un adulto enseguida; nunca uses agua cerca de electricidad.', 'saf_casa_04', 4);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_05', 'EN_CASA', 'Limpieza en la cocina', 'Un adulto está usando un producto de limpieza fuerte en la cocina.', 'Salir o mantenerte a una distancia segura', 'Acercarte a oler el producto|Tocar el envase mientras el adulto lo usa', 'Al usar productos fuertes, es mejor ventilar el espacio y mantener distancia, incluso si un adulto los maneja.', 'saf_casa_05', 5);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_06', 'EN_CASA', 'Pastillas parecidas a caramelos', 'Encuentras unas pastillas sueltas que se parecen a caramelos.', 'No tocarlas y avisar a un adulto', 'Comer una para probar|Guardarlas en tu bolsillo', 'Algunos medicamentos parecen caramelos pero no lo son: nunca los pruebes, avisa siempre a un adulto.', 'saf_casa_06', 6);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_casa_07', 'EN_CASA', 'Olor a gas', 'Sientes un olor extraño parecido a gas en la cocina.', 'Avisar a un adulto de inmediato y salir del lugar', 'Encender un fósforo para ver mejor|Ignorarlo y seguir jugando', 'Ante un olor a gas, nunca enciendas nada: sal del lugar y avisa a un adulto enseguida.', 'saf_casa_07', 7);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_01', 'EN_ESCUELA', 'Símbolo de peligro', 'En el laboratorio del cole ves un frasco con un símbolo de peligro.', 'No tocarlo y decírselo al profesor', 'Abrirlo para ver qué contiene|Moverlo a otra mesa tú mismo', 'Los símbolos de peligro indican que solo un adulto responsable debe manipular ese frasco.', 'saf_esc_01', 8);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_02', 'EN_ESCUELA', 'Mezcla por curiosidad', 'Un compañero quiere mezclar productos de limpieza del laboratorio ''por curiosidad''.', 'Decirle que no lo haga y avisar al profesor', 'Ayudarlo a mezclar|Grabarlo en video sin decir nada', 'Mezclar sustancias sin supervisión puede ser peligroso; siempre debe avisarse a un adulto responsable.', 'saf_esc_02', 9);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_03', 'EN_ESCUELA', 'Derrame en el suelo', 'Se derrama un líquido desconocido en el suelo del laboratorio.', 'Avisar al profesor y alejarte del área', 'Limpiarlo tú mismo con papel|Pisarlo para ver qué es', 'Ante cualquier derrame desconocido, la persona adulta a cargo debe encargarse de limpiarlo con seguridad.', 'saf_esc_03', 10);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_04', 'EN_ESCUELA', 'Gafas protectoras', 'La profesora reparte gafas protectoras antes de un experimento.', 'Ponértelas correctamente antes de empezar', 'Dejarlas a un lado, no son necesarias|Usarlas solo si te acuerdas', 'Las gafas protectoras evitan que salpicaduras lleguen a los ojos: siempre deben usarse cuando se indican.', 'saf_esc_04', 11);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_05', 'EN_ESCUELA', 'Oler directamente', 'Un compañero prueba a oler directamente un frasco de sustancia química.', 'Decirle que aleje el frasco de la nariz y avise al profesor', 'Reírte y no decir nada|Oler tú también para comprobar', 'Nunca se debe oler una sustancia directamente y de cerca; los vapores pueden ser irritantes.', 'saf_esc_05', 12);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_06', 'EN_ESCUELA', 'Alarma de incendios', 'Suena la alarma de incendios durante una clase de ciencias.', 'Salir en orden siguiendo las indicaciones del profesor', 'Quedarte a terminar el experimento|Correr sin avisar a nadie', 'Ante cualquier alarma, lo correcto es salir en orden y seguir siempre las indicaciones de un adulto.', 'saf_esc_06', 13);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_esc_07', 'EN_ESCUELA', 'Correr en el laboratorio', 'Ves a un compañero corriendo dentro del laboratorio escolar.', 'Decirle que camine con calma por seguridad', 'Correr también|No decir nada', 'Correr cerca de mesas con materiales de laboratorio aumenta el riesgo de accidentes y derrames.', 'saf_esc_07', 14);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_01', 'EN_LABORATORIO_VIRTUAL', 'Antes de empezar', 'Antes de cualquier experimento real de ciencias, ¿qué debes hacer primero?', 'Leer las instrucciones y pedir permiso a un adulto', 'Empezar directamente sin leer nada|Improvisar tus propios pasos', 'Leer las instrucciones y contar con la supervisión de un adulto es el primer paso de cualquier experimento real.', 'saf_lab_01', 15);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_02', 'EN_LABORATORIO_VIRTUAL', 'Guardar materiales', 'Terminaste tu experimento real en clase: ¿qué haces con los materiales usados?', 'Guardarlos como indique el profesor', 'Dejarlos donde sea|Llevártelos a casa sin permiso', 'Guardar correctamente los materiales, siguiendo las indicaciones del adulto responsable, es parte de la seguridad.', 'saf_lab_02', 16);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_03', 'EN_LABORATORIO_VIRTUAL', 'Fuego o calor', 'Un experimento del libro requiere usar fuego o una fuente de calor real.', 'Hacerlo solo con un adulto presente', 'Intentarlo a solas con cuidado|Usar velas de tu casa sin avisar', 'Cualquier actividad con fuego o calor real necesita siempre la supervisión directa de un adulto.', 'saf_lab_03', 17);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_04', 'EN_LABORATORIO_VIRTUAL', 'Algo desconocido', 'Un experimento pide usar un material que no reconoces.', 'Preguntar a un adulto qué es antes de usarlo', 'Usarlo igual, seguro no pasa nada|Sustituirlo por otra cosa sin avisar', 'Si no reconoces un material, siempre pregunta antes de usarlo: la curiosidad segura empieza por preguntar.', 'saf_lab_04', 18);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_05', 'EN_LABORATORIO_VIRTUAL', 'Manos sucias', 'Te ensuciaste las manos con una sustancia durante un experimento real.', 'Lavarte las manos con agua y jabón', 'Limpiarte en la ropa|Seguir tocando otras cosas sin lavarte', 'Lavarse las manos después de manipular materiales de laboratorio es un hábito de seguridad básico.', 'saf_lab_05', 19);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_06', 'EN_LABORATORIO_VIRTUAL', 'Solo con un adulto', 'El libro de experimentos dice ''realizar solo con un adulto presente''.', 'Esperar a tener un adulto contigo', 'Hacerlo de todas formas, solo esta vez|Pedirle a un amigo que haga de adulto', 'Esa indicación existe para tu seguridad: siempre debe respetarse tal como está escrita.', 'saf_lab_06', 20);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_lab_07', 'EN_LABORATORIO_VIRTUAL', 'Guardar herramientas', 'Terminaste de usar unas tijeras y pinzas de laboratorio en clase real.', 'Guardarlas en su lugar con cuidado', 'Dejarlas sobre la mesa de cualquier forma|Llevártelas en el bolsillo', 'Guardar bien las herramientas evita accidentes y ayuda a que el siguiente grupo las encuentre en orden.', 'saf_lab_07', 21);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_01', 'PRIMEROS_AUXILIOS_BASICOS', 'Salpicadura en los ojos', 'Un compañero se salpicó los ojos con algo por accidente.', 'Avisar de inmediato a un adulto responsable', 'Decirle que se frote los ojos|Esperar a ver si se le pasa solo', 'Ante cualquier salpicadura en los ojos, se debe avisar inmediatamente a un adulto; nunca frotar.', 'saf_aux_01', 22);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_02', 'PRIMEROS_AUXILIOS_BASICOS', 'Quemadura leve', 'Alguien se quemó ligeramente la mano al tocar algo caliente.', 'Avisar a un adulto para que lo atienda', 'Aplicar hielo directamente y con fuerza|No decir nada, ya se le pasará', 'Las quemaduras, incluso leves, deben ser atendidas por un adulto responsable.', 'saf_aux_02', 23);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_03', 'PRIMEROS_AUXILIOS_BASICOS', 'Mareo repentino', 'Un compañero se sintió mareado durante una actividad.', 'Avisar a un adulto y ayudarlo a sentarse', 'Dejarlo solo hasta que se le pase|Darle algo de comer o beber sin avisar', 'Ante un mareo, lo correcto es avisar a un adulto y acompañar a la persona mientras llega ayuda.', 'saf_aux_03', 24);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_04', 'PRIMEROS_AUXILIOS_BASICOS', 'Algo tragado por accidente', 'Alguien tragó accidentalmente algo que no debía.', 'Avisar a un adulto de inmediato', 'Darle de beber algo para que se le pase|Esperar a ver si se siente mal', 'En estos casos hay que avisar a un adulto inmediatamente; solo un adulto o un profesional debe decidir qué hacer.', 'saf_aux_04', 25);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_05', 'PRIMEROS_AUXILIOS_BASICOS', 'Corte leve', 'Un compañero se cortó levemente con un material del laboratorio.', 'Avisar a un adulto para que lo revise', 'Ignorarlo si no sangra mucho|Cubrirlo con cualquier cosa sin avisar', 'Incluso los cortes leves deben ser revisados por un adulto responsable para curarlos bien.', 'saf_aux_05', 26);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_06', 'PRIMEROS_AUXILIOS_BASICOS', 'Tos por un olor fuerte', 'Alguien empezó a toser mucho después de oler algo fuerte.', 'Alejarlo del lugar y avisar a un adulto', 'Decirle que aguante la respiración|No darle importancia', 'Ante tos o molestia por un olor fuerte, aléjate del área y busca ayuda de un adulto.', 'saf_aux_06', 27);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_aux_07', 'PRIMEROS_AUXILIOS_BASICOS', 'Piel manchada', 'Un compañero se manchó la piel con una sustancia desconocida.', 'Avisar a un adulto para que lo revise', 'Frotar fuerte para quitarlo|Esperar a que se seque solo', 'Ante contacto con una sustancia desconocida en la piel, siempre debe intervenir un adulto responsable.', 'saf_aux_07', 28);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_01', 'ETIQUETAS_Y_SIMBOLOS', 'Símbolo de calavera', 'Ves un símbolo con una calavera en un envase.', 'Entender que significa peligro y no tocarlo', 'Pensar que es solo una decoración|Abrirlo para comprobar', 'El símbolo de calavera indica peligro: nunca debe tocarse ni abrirse sin un adulto.', 'saf_etq_01', 29);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_02', 'ETIQUETAS_Y_SIMBOLOS', 'Símbolo de llama', 'Ves un símbolo de llama en una etiqueta.', 'Saber que el contenido puede ser inflamable', 'Pensar que sirve para encender fuego|Acercarlo a una fuente de calor', 'El símbolo de llama avisa que el producto puede arder fácilmente: debe alejarse del calor y del fuego.', 'saf_etq_02', 30);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_03', 'ETIQUETAS_Y_SIMBOLOS', 'Símbolo corrosivo', 'Ves un símbolo con una mano y un líquido goteando sobre ella.', 'Entender que el producto puede dañar la piel y evitarlo', 'Tocarlo para comprobar si es cierto|Ignorarlo por completo', 'Ese símbolo indica que el producto es corrosivo y puede dañar la piel: nunca debe tocarse directamente.', 'saf_etq_03', 31);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_04', 'ETIQUETAS_Y_SIMBOLOS', 'Símbolo de reciclaje', 'Ves el símbolo de reciclaje en un envase vacío.', 'Depositarlo en el contenedor correcto', 'Tirarlo en cualquier lugar|Quemarlo', 'El símbolo de reciclaje indica que el envase, una vez vacío y limpio, puede reciclarse correctamente.', 'saf_etq_04', 32);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_05', 'ETIQUETAS_Y_SIMBOLOS', 'Signo de exclamación', 'Ves un signo de exclamación en una etiqueta de producto.', 'Tener cuidado extra y leer las instrucciones', 'Ignorarlo, no parece grave|Usar el doble de producto', 'El signo de exclamación pide precaución: conviene leer bien las instrucciones antes de usar el producto.', 'saf_etq_05', 33);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_06', 'ETIQUETAS_Y_SIMBOLOS', 'Envase sin etiqueta', 'Ves un envase de líquido que no tiene ninguna etiqueta.', 'No usarlo y avisar a un adulto', 'Adivinar qué es por el color|Probarlo con cuidado', 'Un envase sin etiqueta es un misterio: nunca se debe usar ni probar, siempre avisar a un adulto.', 'saf_etq_06', 34);
INSERT INTO safety_scenario (id, category, title, situationText, correctActionText, distractorActionCsv, explanation, iconKey, orderIndex) VALUES ('saf_etq_07', 'ETIQUETAS_Y_SIMBOLOS', 'Símbolo no comestible', 'Ves un símbolo de ''no comestible'' en un producto casero.', 'Recordar que nunca se debe comer ni probar', 'Pensar que es solo para adultos|Probarlo si tiene buen color', 'El símbolo de ''no comestible'' aplica para todos, niños y adultos: nunca debe llevarse a la boca.', 'saf_etq_07', 35);

-- Insignias
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_primeros_pasos', 'Primeros Pasos', 'Completaste tu primer experimento en QuimicAtomix.', 'PROGRESO', 'badge_primeros_pasos', 'EXPERIMENTOS_COMPLETADOS', 1, 1);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_curioso', 'Explorador Curioso', 'Completaste 10 experimentos del laboratorio.', 'PROGRESO', 'badge_curioso', 'EXPERIMENTOS_COMPLETADOS', 10, 2);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_maestro_mezclas', 'Maestro de las Mezclas', 'Dominaste por completo un tema del laboratorio.', 'DOMINIO', 'badge_maestro_mezclas', 'TEMA_DOMINADO', 1, 3);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_racha', 'Racha de Genio', 'Encadenaste 5 aciertos seguidos sin fallar.', 'ESPECIAL', 'badge_racha', 'RACHA_ACIERTOS', 5, 4);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_guardian', 'Guardián de la Seguridad', 'Completaste 10 escenarios de seguridad del laboratorio.', 'SEGURIDAD', 'badge_guardian', 'ESCENARIOS_SEGURIDAD', 10, 5);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_arquitecto', 'Arquitecto Molecular', 'Construiste 5 moléculas distintas correctamente.', 'COLECCION', 'badge_arquitecto', 'MOLECULAS_CONSTRUIDAS', 5, 6);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_nivel5', 'Explorador Nivel 5', 'Alcanzaste el nivel 5 en tu perfil de laboratorio.', 'PROGRESO', 'badge_nivel5', 'NIVEL_ALCANZADO', 5, 7);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_coleccionista', 'Coleccionista de Estrellas', 'Acumulaste 50 estrellas en total.', 'COLECCION', 'badge_coleccionista', 'ESTRELLAS_TOTALES', 50, 8);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_cientifico', 'Científico Completo', 'Completaste 40 experimentos del laboratorio.', 'DOMINIO', 'badge_cientifico', 'EXPERIMENTOS_COMPLETADOS', 40, 9);
INSERT INTO badge (id, name, description, category, iconKey, criteriaType, criteriaValue, orderIndex) VALUES ('badge_leyenda', 'Leyenda del Laboratorio', 'Dominaste por completo los seis temas de QuimicAtomix.', 'ESPECIAL', 'badge_leyenda', 'TEMA_DOMINADO', 6, 10);

-- Equipamiento de laboratorio
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_bata', 'Bata de laboratorio', 'La primera prenda de todo científico responsable.', 'equip_bata', 'COMUN', 'EXPERIMENTOS_COMPLETADOS', 1, 1);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_gafas', 'Gafas protectoras', 'Protegen los ojos durante cualquier experimento.', 'equip_gafas', 'COMUN', 'EXPERIMENTOS_COMPLETADOS', 5, 2);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_guantes', 'Guantes de laboratorio', 'Ideales para manipular materiales con cuidado.', 'equip_guantes', 'COMUN', 'ESCENARIOS_SEGURIDAD', 5, 3);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_vaso', 'Vaso de precipitados', 'Un clásico para medir y observar líquidos.', 'equip_vaso', 'POCO_COMUN', 'EXPERIMENTOS_COMPLETADOS', 10, 4);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_matraz', 'Matraz Erlenmeyer', 'Perfecto para mezclas que necesitan agitarse con cuidado.', 'equip_matraz', 'POCO_COMUN', 'TEMA_DOMINADO', 1, 5);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_mechero', 'Mechero virtual', 'Una fuente de calor conceptual, siempre segura y simulada.', 'equip_mechero', 'POCO_COMUN', 'EXPERIMENTOS_COMPLETADOS', 20, 6);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_microscopio', 'Microscopio', 'Te permite imaginar el mundo diminuto de los átomos.', 'equip_microscopio', 'RARO', 'NIVEL_ALCANZADO', 4, 7);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_tabla', 'Tabla periódica de bolsillo', 'Un mapa de todos los átomos que has conocido.', 'equip_tabla', 'RARO', 'MOLECULAS_CONSTRUIDAS', 8, 8);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_iman', 'Kit de imanes', 'Ideal para descubrir qué materiales son magnéticos.', 'equip_iman', 'RARO', 'RACHA_ACIERTOS', 8, 9);
INSERT INTO lab_equipment (id, name, description, iconKey, rarity, unlockCriteriaType, unlockCriteriaValue, orderIndex) VALUES ('equip_medalla', 'Medalla dorada del laboratorio', 'El máximo reconocimiento de QuimicAtomix.', 'equip_medalla', 'LEGENDARIO', 'TEMA_DOMINADO', 6, 10);

-- Ejemplo de perfil y progreso de un jugador de muestra (no forma parte del seed real de la app)
INSERT INTO user_profile (id, alias, avatarId, createdAt, lastActiveAt, totalXp, level) VALUES (1, 'Explorador', 0, 1700000000000, 1700000000000, 120, 2);
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'estados', 0, 0, 0, 'DISPONIBLE');
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'mezclas', 0, 0, 0, 'DISPONIBLE');
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'separacion', 0, 0, 0, 'DISPONIBLE');
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'atomos', 0, 0, 0, 'DISPONIBLE');
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'moleculas', 0, 0, 0, 'DISPONIBLE');
INSERT INTO progress (userId, topicId, experimentsCompleted, experimentsTotal, starsTotal, mastery) VALUES (1, 'reacciones', 0, 0, 0, 'DISPONIBLE');